import { useState } from 'react';
import { ClipboardCopy, Check, Mail, FileDown, FileText } from 'lucide-react';
import { answerExportUrl } from '../lib/api';

function formatAnswerForSharing(question, answerText, citations) {
  const timestamp = new Date().toLocaleString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  let formatted = `Question: ${question}\n\n`;
  formatted += `Answer:\n${answerText}\n\n`;

  if (citations && citations.length > 0) {
    formatted += `Sources:\n`;
    citations.forEach((cit, i) => {
      const id = cit.citation_id || i + 1;
      formatted += `[${id}] ${cit.title}, ${cit.source_type}\n`;
    });
  }

  formatted += `\n---\nGenerated by DCMS Evidence Bot\n${timestamp}`;
  return formatted;
}

export default function ShareButtons({ question, answerText, citations, requestId }) {
  const [copied, setCopied] = useState(false);

  if (!answerText) return null;

  const handleCopy = async () => {
    const text = formatAnswerForSharing(question, answerText, citations);

    try {
      await navigator.clipboard.writeText(text);
    } catch {
      const textarea = document.createElement('textarea');
      textarea.value = text;
      textarea.style.position = 'fixed';
      textarea.style.opacity = '0';
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
    }

    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleEmail = () => {
    const text = formatAnswerForSharing(question, answerText, citations);
    const truncated = question.length > 50 ? question.substring(0, 50) + '...' : question;
    const subject = `DCMS Evidence Bot - Answer to "${truncated}"`;
    window.location.href = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(text)}`;
  };

  return (
    <div className="flex flex-wrap gap-2 mt-4">
      <button
        onClick={handleCopy}
        aria-label={copied ? 'Copied to clipboard' : 'Copy answer to clipboard'}
        className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium rounded-md border
          dark:border-dark-500 dark:text-warm-300 dark:hover:bg-dark-600
          light:border-warm-300 light:text-warm-500 light:hover:bg-warm-100
          transition-colors cursor-pointer"
      >
        {copied ? (
          <>
            <Check size={14} />
            Copied!
          </>
        ) : (
          <>
            <ClipboardCopy size={14} />
            Copy to Clipboard
          </>
        )}
      </button>

      <button
        onClick={handleEmail}
        aria-label="Email this answer"
        className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium rounded-md border
          dark:border-dark-500 dark:text-warm-300 dark:hover:bg-dark-600
          light:border-warm-300 light:text-warm-500 light:hover:bg-warm-100
          transition-colors cursor-pointer"
      >
        <Mail size={14} />
        Email This Answer
      </button>

      {requestId && (
        <>
          <a
            href={answerExportUrl(requestId, 'html')}
            target="_blank"
            rel="noopener"
            aria-label="Download this answer as HTML"
            className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium rounded-md border
              dark:border-dark-500 dark:text-warm-300 dark:hover:bg-dark-600
              light:border-warm-300 light:text-warm-500 light:hover:bg-warm-100
              transition-colors cursor-pointer"
          >
            <FileText size={14} />
            Download HTML
          </a>
          <a
            href={answerExportUrl(requestId, 'pdf')}
            target="_blank"
            rel="noopener"
            aria-label="Download this answer as PDF"
            className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium rounded-md border
              dark:border-dark-500 dark:text-warm-300 dark:hover:bg-dark-600
              light:border-warm-300 light:text-warm-500 light:hover:bg-warm-100
              transition-colors cursor-pointer"
          >
            <FileDown size={14} />
            Download PDF
          </a>
        </>
      )}
    </div>
  );
}
